apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-comm

resources:
  - namespace.yaml
  - configmap.yaml
  - mongo.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

images:
  - name: ghcr.io/kash571-pcbpo/e-comm-mern/backend
    newTag: latest
  - name: ghcr.io/kash571-pcbpo/e-comm-mern/frontend
    newTag: latest
